version: "3.8"
services:
  backend:
    build: ./backend-api
    ports:
      - "3000:3000"
    env_file:
      - ./backend-api/.env
  frontend:
    build: ./front-end
    ports:
      - "5173:5173"
    environment:
      - VITE_BE_URL=http://backend:3000
